[{"items": [{"tags": ["keras", "tensorflow2.0"], "owner": {"account_id": 108161, "reputation": 5951, "user_id": 287238, "user_type": "registered", "accept_rate": 75, "profile_image": "https://i.stack.imgur.com/oQJH2.jpg?s=256&g=1", "display_name": "mathtick", "link": "https://stackoverflow.com/users/287238/mathtick"}, "is_answered": false, "view_count": 44, "answer_count": 0, "score": 1, "last_activity_date": 1555095135, "creation_date": 1555095135, "question_id": 55657910, "content_license": "CC BY-SA 4.0", "link": "https://stackoverflow.com/questions/55657910/keras-categorical-entropy-outputs-shape-unknown", "title": "Keras categorical_entropy outputs shape unknown?", "body": "<pre><code>In [43]: x = keras.Input(shape=(10,))\n\nIn [44]: keras.losses.categorical_crossentropy(x, x, from_logits=True)\nOut[44]: &lt;tf.Tensor 'softmax_cross_entropy_with_logits_11/Reshape_2:0' shape=&lt;unknown&gt; dtype=float32&gt;\n</code></pre>\n\n<p>Pretty much says it all. End up shape the usual TypeError: object of type 'NoneType' has no len() with this.</p>\n"}], "has_more": false, "quota_max": 300, "quota_remaining": 83}]