[{"items": [{"tags": ["python", "python-3.x", "machine-learning", "keras", "tf.keras"], "owner": {"user_type": "does_not_exist", "display_name": "user5597655"}, "is_answered": true, "view_count": 148, "accepted_answer_id": 57416158, "answer_count": 2, "score": -1, "last_activity_date": 1583339540, "creation_date": 1565276158, "last_edit_date": 1583339540, "question_id": 57415484, "content_license": "CC BY-SA 4.0", "link": "https://stackoverflow.com/questions/57415484/keras-simple-feed-forward-network-input-shape-error", "title": "Keras simple feed-forward network input shape error", "body": "<p>I am trying to train a very simple feed forward network in Keras. I want to give the network 1800 numbers, and have it activate 1 of 6 outputs. </p>\n\n<p>My model is set up as follows:</p>\n\n<pre><code>model = keras.Sequential([\n    keras.layers.Dense(256, input_dim = 1800, activation=tf.nn.relu),\n    keras.layers.Dense(48, activation=tf.nn.relu),\n    keras.layers.Dense(6, activation=tf.nn.softmax)\n])\n</code></pre>\n\n<p>My data is set up as follows:</p>\n\n<p>It is split into two Python lists <code>training_data</code> and <code>training_labels</code>.</p>\n\n<p>An element from <code>training_labels</code> is a Python list containing 6 numbers like this:</p>\n\n<pre><code>[0, 0, 0, 0, 1, 0]\n</code></pre>\n\n<p>An element from <code>training_data</code> is a Python list containing 1800 numbers like this:</p>\n\n<pre><code>[15, 155, 1200, 1, ... ]\n</code></pre>\n\n<p>There are 1500 examples in total.</p>\n\n<p>To fit the model, I am doing:</p>\n\n<pre><code>model.fit(training_data, training_labels, batch_size=1)\n</code></pre>\n\n<p>But I get the error: </p>\n\n<pre><code>ValueError: Error when checking input: expected dense_1_input to have shape (None, 1800) but got array with shape (150, 1)\n</code></pre>\n"}], "has_more": false, "quota_max": 300, "quota_remaining": 39}]