[{"items": [{"tags": ["tensorflow", "tensorflow-datasets"], "owner": {"account_id": 3948330, "reputation": 5043, "user_id": 3259896, "user_type": "registered", "accept_rate": 60, "profile_image": "https://www.gravatar.com/avatar/641c30a7b383022f22b53c8cedb04e3f?s=256&d=identicon&r=PG&f=1", "display_name": "SantoshGupta7", "link": "https://stackoverflow.com/users/3259896/santoshgupta7"}, "is_answered": true, "view_count": 201, "accepted_answer_id": 62298818, "answer_count": 1, "score": 1, "last_activity_date": 1591867042, "creation_date": 1591649941, "question_id": 62271078, "content_license": "CC BY-SA 4.0", "link": "https://stackoverflow.com/questions/62271078/how-to-develop-a-tf-data-object-from-a-generator-that-only-outputs-a-list-of-arr", "title": "How to develop a tf.data object from a generator that only outputs a list of arrays?", "body": "<p>I am trying to develop a tf.data object that yields a list of arrays, but I am getting a data mismatch error. Here's my attempt</p>\n\n<pre><code>def labelGen():\n    yield tf.constant([1, 0], dtype=tf.int64), tf.constant([1, 0], dtype=tf.int64), tf.constant([0, 1], dtype=tf.int64), tf.constant([0, 1], dtype=tf.int64)\n\nLabeldataset = tf.data.Dataset.from_generator(\n     labelGen, (tf.int64, tf.int64, tf.int64, tf.int64, tf.int64), ([], [], [], [], []) )\n\nlist(Labeldataset.take(1))\n</code></pre>\n\n<p>And this is the error I get </p>\n\n<blockquote>\n  <p>InvalidArgumentError: TypeError: <code>generator</code> yielded an element that did not match the expected structure. The expected structure was (tf.int64, tf.int64, tf.int64, tf.int64, tf.int64), but the yielded element was (, , , ).\n  Traceback (most recent call last):</p>\n</blockquote>\n"}], "has_more": false, "quota_max": 300, "quota_remaining": 81}]