[{"items": [{"tags": ["python", "tensorflow", "keras", "tensorflow2.0", "tf.keras"], "owner": {"account_id": 6956681, "reputation": 1056, "user_id": 5337505, "user_type": "registered", "accept_rate": 67, "profile_image": "https://lh5.googleusercontent.com/-F4WMV67MG-o/AAAAAAAAAAI/AAAAAAAABGA/b-vMtZ0piXI/photo.jpg?sz=256", "display_name": "Siladittya", "link": "https://stackoverflow.com/users/5337505/siladittya"}, "is_answered": false, "view_count": 1129, "answer_count": 1, "score": 3, "last_activity_date": 1605125177, "creation_date": 1601720430, "last_edit_date": 1601721694, "question_id": 64183141, "content_license": "CC BY-SA 4.0", "link": "https://stackoverflow.com/questions/64183141/valueerror-you-called-set-weightsweights-on-optimizer-rmsprop-with-a-weight", "title": "ValueError: You called `set_weights(weights)` on optimizer RMSprop with a weight list of length 3, but the optimizer was expecting 0 weights", "body": "<p>I have a saved model in 'h5' format. I am trying to resume training and trying to load the weights of the optimizer after compiling the model using</p>\n<p><code>model.optimizer.set_weights(weights_list)</code></p>\n<p>where <code>weights_list</code> is a list of numpy arrays containing the optimizer weights that I manually extracted from the h5 file.</p>\n<p>But I am getting the above error.</p>\n<p>When I try <code>model.optimizer.get_weights()</code> I am getting an empty list.</p>\n<p>I want to know how to initialize the optimizer weights without any error.</p>\n<p>However, if I do</p>\n<p><code>model = tf.keras.model.load_model('~/modelname.h5',custom_objects={},compile=True)</code></p>\n<p>It works, that is I can resume training with the previously saved weights.</p>\n<p>However, <code>tf.keras.models.load_model</code> doesn't always work and sometimes it requires one to build the model and use <code>load_weights</code> to initialize the model.</p>\n"}], "has_more": false, "quota_max": 300, "quota_remaining": 22}]