[{"items": [{"tags": ["tensorflow", "keras"], "owner": {"account_id": 12699750, "reputation": 109, "user_id": 9226944, "user_type": "registered", "profile_image": "https://www.gravatar.com/avatar/325127a0db4df5c81dce8f9025e6876b?s=256&d=identicon&r=PG&f=1", "display_name": "mricdev", "link": "https://stackoverflow.com/users/9226944/mricdev"}, "is_answered": false, "view_count": 341, "answer_count": 0, "score": 1, "last_activity_date": 1620753241, "creation_date": 1620751611, "last_edit_date": 1620753241, "question_id": 67491074, "content_license": "CC BY-SA 4.0", "link": "https://stackoverflow.com/questions/67491074/tensorflow2-attempt-to-convert-a-value-none-with-an-unsupported-type-class", "title": "Tensorflow2, Attempt to convert a value (None) with an unsupported type (&lt;class &#39;NoneType&#39;&gt;) to a Tensor", "body": "<p>I am trying to compute a sum of gradients (that will later be used in the network optimizer), here is the code:</p>\n<pre><code>with tf.GradientTape(persistent=True) as tape:\n    log_proba = tf.math.log(0.7)\n    val_acc = tf.constant(0.6)\n    grad_log_proba = tape.gradient(log_proba, controller.trainable_weights)\n    sum_over_choices = grad_log_proba * val_acc\n</code></pre>\n<p>Which gives the error:</p>\n<blockquote>\n<p>ValueError: Attempt to convert a value (None) with an unsupported type (&lt;class 'NoneType'&gt;) to a Tensor.</p>\n</blockquote>\n<p>I looked at other posts but I could not find an answer.</p>\n<p>Any idea?</p>\n<p>[<strong>UPDATE</strong>]</p>\n<p>Here is the entire stack trace:</p>\n<blockquote>\n<p>File &quot;Controller.py&quot;, line 368, in main</p>\n<p>sum_over_choices = grad_log_proba * val_acc</p>\n<p>File\n&quot;C:\\Users\\aymer.conda\\envs\\PythonCPU\\lib\\site-packages\\tensorflow\\python\\ops\\math_ops.py&quot;,\nline 1155, in r_binary_op_wrapper</p>\n<p>x = ops.convert_to_tensor(x, dtype=y.dtype.base_dtype, name=&quot;x&quot;)</p>\n<p>File\n&quot;C:\\Users\\aymer.conda\\envs\\PythonCPU\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py&quot;,\nline 1499, in convert_to_tensor</p>\n<p>ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)</p>\n<p>File\n&quot;C:\\Users\\aymer.conda\\envs\\PythonCPU\\lib\\site-packages\\tensorflow\\python\\framework\\constant_op.py&quot;,\nline 338, in _constant_tensor_conversion_function</p>\n<p>return constant(v, dtype=dtype, name=name)</p>\n<p>File\n&quot;C:\\Users\\aymer.conda\\envs\\PythonCPU\\lib\\site-packages\\tensorflow\\python\\framework\\constant_op.py&quot;,\nline 263, in constant</p>\n<p>return _constant_impl(value, dtype, shape, name, verify_shape=False,</p>\n<p>File\n&quot;C:\\Users\\aymer.conda\\envs\\PythonCPU\\lib\\site-packages\\tensorflow\\python\\framework\\constant_op.py&quot;,\nline 275, in _constant_impl</p>\n<p>return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)</p>\n<p>File\n&quot;C:\\Users\\aymer.conda\\envs\\PythonCPU\\lib\\site-packages\\tensorflow\\python\\framework\\constant_op.py&quot;,\nline 300, in _constant_eager_impl</p>\n<p>t = convert_to_eager_tensor(value, ctx, dtype)</p>\n<p>File\n&quot;C:\\Users\\aymer.conda\\envs\\PythonCPU\\lib\\site-packages\\tensorflow\\python\\framework\\constant_op.py&quot;,\nline 98, in convert_to_eager_tensor</p>\n<p>return ops.EagerTensor(value, ctx.device_name, dtype)</p>\n<p>ValueError: Attempt to convert a value (None) with an unsupported type\n(&lt;class 'NoneType'&gt;) to a Tensor.</p>\n</blockquote>\n<p>p.s: I already posted this one hour ago on another account but I deleted it by mistake, so here it is</p>\n"}], "has_more": false, "quota_max": 300, "quota_remaining": 146}]